export const REQUEST_COUNTRIES='REQUEST_COUNTRIES'
export const GET_COUNTRIES_FAILURE='GET_COUNTRIES_FAILURE'
export const GET_COUNTRIES_SUCCESS='GET_COUNTRIES_SUCCESS'

export const TOGGLE_COUNTRY_SHOWING = 'TOGGLE_COUNTRY_SHOWING'
export const TOGGLE_HOME_SHOWING = 'TOGGLE_HOME_SHOWING'